# Generated by Django 2.1.1 on 2018-11-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('url', models.CharField(default='', max_length=100, verbose_name='URL')),
                ('req_method', models.CharField(default='', max_length=10, verbose_name='请求方法')),
                ('req_type', models.CharField(default='', max_length=10, verbose_name='请求类型')),
                ('req_header', models.TextField(default='', verbose_name='Header')),
                ('req_param', models.TextField(default='', verbose_name='请求参数')),
                ('rsp_assert', models.TextField(default='', verbose_name='验证')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Module')),
            ],
        ),
    ]
